nmHoistingLimits: workspaces

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-3.2.0-rc.9.cjs

changesetBaseRefs:
  - "gen-0"
  - "origin/gen-0"
  - "upstream/gen-0"

npmRegistryServer: http://localhost:4873/
npmPublishRegistry: http://localhost:4873/

unsafeHttpWhitelist:
  - localhost
